### ISSUE TITLE
Why skip long utterances?

### ISSUE THREAD

**Issue by JRMeyer** [jxzhanggg/nonparaSeq2seqVC_code#3]
It seems the training code skips utterances longer that `1,000` frames:

https://github.com/jxzhanggg/nonparaSeq2seqVC_code/blob/758ecb65f30128314bd3f07ca180a96154181b4e/pre-train/reader/reader.py#L17

Does this mean you skip all utterances longer than ~12.5 seconds (in the paper `12.5ms` is the reported skip length for calculating the spectogram)? If so, why?

**Comment by jxzhanggg** [comment]
Yes, you are right. I wrote so because I found the serveral quite long utterance may cause padding the batch too long. Therefore, these batch will make the out of memory problem (or you have to use small batch size).  Eliminating these super long utterances will not affect training too much, just slightly reducing training corpus.
