### ISSUE TITLE
GPU memory requirements

### ISSUE THREAD

**Issue by ivancarapinha** [jxzhanggg/nonparaSeq2seqVC_code#32]
Hello,
What are the GPU memory requirements to use the model? I am using a GeForce GTX TITAN X with 12G of RAM and I got the following error:
`RuntimeError: CUDA out of memory. Tried to allocate 132.88 MiB (GPU 0; 11.93 GiB total capacity; 11.03 GiB already allocated; 107.44 MiB free; 308.29 MiB cached)
`

Do you have any suggestions about how to overcome this problem?
Thank you.

**Comment by jxzhanggg** [comment]
Hi,
12G RAM should be enough for training the model. I trained my model with a batch size of 32 on a 12 G GTX1080Ti. Because a training batch is padedd to the longest sequence, super long utterances will cause the OOM problem. You can filter out these utterances by setting a threshold. For example, you can drop all utterances exceeding 10 seconds in training set.

**Comment by ivancarapinha** [comment]
I will definitely try that. Thanks for the recommendation!
